# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alan_haritasi_ekrani.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1055, 859)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.harita_resim_label = QtWidgets.QLabel(self.centralwidget)
        self.harita_resim_label.setGeometry(QtCore.QRect(4, -5, 1051, 811))
        self.harita_resim_label.setText("")
        self.harita_resim_label.setPixmap(QtGui.QPixmap("arka_plan6.jpg"))
        self.harita_resim_label.setScaledContents(True)
        self.harita_resim_label.setObjectName("harita_resim_label")
        self.btn_geri_alan = QtWidgets.QPushButton(self.centralwidget)
        self.btn_geri_alan.setGeometry(QtCore.QRect(30, 690, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_geri_alan.setFont(font)
        self.btn_geri_alan.setObjectName("btn_geri_alan")
        self.btn_cikis_alan = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cikis_alan.setGeometry(QtCore.QRect(890, 720, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cikis_alan.setFont(font)
        self.btn_cikis_alan.setObjectName("btn_cikis_alan")
        self.lbl_harita_baslik = QtWidgets.QLabel(self.centralwidget)
        self.lbl_harita_baslik.setGeometry(QtCore.QRect(-40, -10, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_harita_baslik.setFont(font)
        self.lbl_harita_baslik.setObjectName("lbl_harita_baslik")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_geri_alan.setText(_translate("MainWindow", "Geri"))
        self.btn_cikis_alan.setText(_translate("MainWindow", "Çıkış"))
        self.lbl_harita_baslik.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Hayvanat Bahçesi Haritası</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
