# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beslenme_saatleri_ekrani.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(4, 5, 1091, 781))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("arka_plan7.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lbl_beslenme_saatleri_baslik = QtWidgets.QLabel(self.centralwidget)
        self.lbl_beslenme_saatleri_baslik.setGeometry(QtCore.QRect(340, 10, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_beslenme_saatleri_baslik.setFont(font)
        self.lbl_beslenme_saatleri_baslik.setObjectName("lbl_beslenme_saatleri_baslik")
        self.btn_geri_beslenme = QtWidgets.QPushButton(self.centralwidget)
        self.btn_geri_beslenme.setGeometry(QtCore.QRect(20, 670, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_geri_beslenme.setFont(font)
        self.btn_geri_beslenme.setObjectName("btn_geri_beslenme")
        self.btn_cikis_beslenme = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cikis_beslenme.setGeometry(QtCore.QRect(920, 680, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cikis_beslenme.setFont(font)
        self.btn_cikis_beslenme.setObjectName("btn_cikis_beslenme")
        self.tbl_beslenme_saatleri = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_beslenme_saatleri.setGeometry(QtCore.QRect(200, 80, 641, 511))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_beslenme_saatleri.setFont(font)
        self.tbl_beslenme_saatleri.setColumnCount(6)
        self.tbl_beslenme_saatleri.setObjectName("tbl_beslenme_saatleri")
        self.tbl_beslenme_saatleri.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_beslenme_saatleri.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_beslenme_saatleri.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_beslenme_saatleri.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_beslenme_saatleri.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_beslenme_saatleri.setHorizontalHeaderItem(4, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_beslenme_saatleri_baslik.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">BESLENME SAATLERİ</p></body></html>"))
        self.btn_geri_beslenme.setText(_translate("MainWindow", "Geri"))
        self.btn_cikis_beslenme.setText(_translate("MainWindow", "Çıkış"))
        item = self.tbl_beslenme_saatleri.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hayvan Türü"))
        item = self.tbl_beslenme_saatleri.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Beslenme Saati"))
        item = self.tbl_beslenme_saatleri.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Yem Türü"))
        item = self.tbl_beslenme_saatleri.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Miktar (kg)"))
        item = self.tbl_beslenme_saatleri.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Notlar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
