# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diyetler_ekrani.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 828)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(4, 5, 1081, 781))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("arka_plan2.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lbl_diyetler_baslik = QtWidgets.QLabel(self.centralwidget)
        self.lbl_diyetler_baslik.setGeometry(QtCore.QRect(370, 10, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_diyetler_baslik.setFont(font)
        self.lbl_diyetler_baslik.setObjectName("lbl_diyetler_baslik")
        self.btn_geri_diyetler = QtWidgets.QPushButton(self.centralwidget)
        self.btn_geri_diyetler.setGeometry(QtCore.QRect(20, 670, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_geri_diyetler.setFont(font)
        self.btn_geri_diyetler.setObjectName("btn_geri_diyetler")
        self.btn_cikis_diyetler = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cikis_diyetler.setGeometry(QtCore.QRect(930, 680, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cikis_diyetler.setFont(font)
        self.btn_cikis_diyetler.setObjectName("btn_cikis_diyetler")
        self.lbl_diyetler_icerik = QtWidgets.QLabel(self.centralwidget)
        self.lbl_diyetler_icerik.setGeometry(QtCore.QRect(260, 70, 511, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_diyetler_icerik.setFont(font)
        self.lbl_diyetler_icerik.setObjectName("lbl_diyetler_icerik")
        self.tbl_diyetler = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_diyetler.setGeometry(QtCore.QRect(245, 160, 551, 411))
        self.tbl_diyetler.setObjectName("tbl_diyetler")
        self.tbl_diyetler.setColumnCount(0)
        self.tbl_diyetler.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_diyetler_baslik.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">DİYET LİSTELERİ</p></body></html>"))
        self.btn_geri_diyetler.setText(_translate("MainWindow", "Geri"))
        self.btn_cikis_diyetler.setText(_translate("MainWindow", "Çıkış"))
        self.lbl_diyetler_icerik.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Hayvan diyet listeleri burada gösterilecektir.</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
