# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ana_ekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1046, 726)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-image: url(arka_plan2.jpg); /* Dosya adını direkt veriyoruz */\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 0, 861, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.btn_ziyaretci = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ziyaretci.setGeometry(QtCore.QRect(60, 410, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_ziyaretci.setFont(font)
        self.btn_ziyaretci.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ziyaretci.setObjectName("btn_ziyaretci")
        self.btn_calisan_giris = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calisan_giris.setGeometry(QtCore.QRect(790, 410, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_calisan_giris.setFont(font)
        self.btn_calisan_giris.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_calisan_giris.setObjectName("btn_calisan_giris")
        self.background_label = QtWidgets.QLabel(self.centralwidget)
        self.background_label.setGeometry(QtCore.QRect(0, -10, 1051, 701))
        self.background_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.background_label.setText("")
        self.background_label.setPixmap(QtGui.QPixmap("arka_plan2.jpg.jpg"))
        self.background_label.setScaledContents(True)
        self.background_label.setObjectName("background_label")
        self.lbl_calisma_saatleri = QtWidgets.QLabel(self.centralwidget)
        self.lbl_calisma_saatleri.setGeometry(QtCore.QRect(10, 100, 781, 191))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_calisma_saatleri.setFont(font)
        self.lbl_calisma_saatleri.setObjectName("lbl_calisma_saatleri")
        self.btn_cikis_ana = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cikis_ana.setGeometry(QtCore.QRect(850, 580, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cikis_ana.setFont(font)
        self.btn_cikis_ana.setObjectName("btn_cikis_ana")
        self.background_label.raise_()
        self.label.raise_()
        self.btn_ziyaretci.raise_()
        self.btn_calisan_giris.raise_()
        self.lbl_calisma_saatleri.raise_()
        self.btn_cikis_ana.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1046, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "HAYVANAT BAHÇESİ OTOMASYONU"))
        self.btn_ziyaretci.setText(_translate("MainWindow", "Ziyaretçi"))
        self.btn_calisan_giris.setText(_translate("MainWindow", "Çalışan"))
        self.lbl_calisma_saatleri.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">HAFTA İÇİ</span></p><p><span style=\" font-size:10pt; font-style:italic;\">AÇILIŞ:Açılış: 09:00 - Kapanış: 20:00</span></p><p><br/></p><p><span style=\" font-size:14pt; font-weight:600;\">HAFTA SONU</span><br/><span style=\" font-size:10pt; font-style:italic;\">AÇILIŞ:Açılış: 09:00 - Kapanış: 22:00 </span></p></body></html>"))
        self.btn_cikis_ana.setText(_translate("MainWindow", "Çıkış"))
