# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ziyaretci_ekrani.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(924, 640)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(280, 30, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-6, -5, 931, 631))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("arka_plan2.jpg.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.btn_beslenme_saatleri
 = QtWidgets.QPushButton(Form)
        self.btn_beslenme_saatleri
.setGeometry(QtCore.QRect(20, 320, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_beslenme_saatleri
.setFont(font)
        self.btn_beslenme_saatleri
.setObjectName("btn_beslenme_saatleri\n"
"")
        self.btn_alan_haritasi = QtWidgets.QPushButton(Form)
        self.btn_alan_haritasi.setGeometry(QtCore.QRect(20, 380, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_alan_haritasi.setFont(font)
        self.btn_alan_haritasi.setObjectName("btn_alan_haritasi")
        self.btn_geri_ziyaretci = QtWidgets.QPushButton(Form)
        self.btn_geri_ziyaretci.setGeometry(QtCore.QRect(30, 500, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_geri_ziyaretci.setFont(font)
        self.btn_geri_ziyaretci.setObjectName("btn_geri_ziyaretci")
        self.btn_cikis_ziyaretci = QtWidgets.QPushButton(Form)
        self.btn_cikis_ziyaretci.setGeometry(QtCore.QRect(700, 500, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cikis_ziyaretci.setFont(font)
        self.btn_cikis_ziyaretci.setObjectName("btn_cikis_ziyaretci")
        self.label_2.raise_()
        self.label.raise_()
        self.btn_beslenme_saatleri
.raise_()
        self.btn_alan_haritasi.raise_()
        self.btn_geri_ziyaretci.raise_()
        self.btn_cikis_ziyaretci.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Ziyaretçi Ana Sayfası"))
        self.btn_beslenme_saatleri
.setText(_translate("Form", "Beslenme Saatleri"))
        self.btn_alan_haritasi.setText(_translate("Form", "Alan Haritası"))
        self.btn_geri_ziyaretci.setText(_translate("Form", "Geri"))
        self.btn_cikis_ziyaretci.setText(_translate("Form", "Çıkış"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
